const dataProject = [
  {
    src: '/img/imgcardcinepolis.jpg',
    alt: 'capa do site de filmes',
    title: 'cinepolis',
    h3: 'Cinepolis',
    p: 'Pagina que traz informações sobre os filmes já lançados incluindo os que estão em cartaz',
    href_site: 'https://cinepolis-tmdb.vercel.app/',
    txt_site: 'Site',
    href_git: 'https://github.com/Eliel-Silva-dev/cinepolis_tmdb',
    txt_git: 'Repositório',
    status: true,
  },
  {
    src: '/img/imgcardpadariavorosa.jpg',
    alt: 'Imagem ilustrativa da padaria vo rosa',
    title: 'padaria vo rosa',
    h3: 'Padaria Vó Rosa',
    p: 'Este projeto tem como objetivo apresentar, aos clientes, informações sobre o estabelecimento e sobre os produtos mais vendidos pela Padaria.',
    href_site: 'https://padaria-vo-rosa.vercel.app/',
    txt_site: 'Site',
    href_git: 'https://github.com/Eliel-Silva-dev/padaria-vo-rosa',
    txt_git: 'Repositório',
    status: true,
  },
  {
    src: '/img/imgcardfilmesonline.jpg',
    alt: 'Imagem ilustrativa da página de filmes',
    title: 'Página de filmes',
    h3: 'Filmes online',
    p: 'Página de filmes. Tenha acesso as informações do melhores filmes lançados, seu orçamento, receita e uma breve descrição.',
    href_site: 'https://filmes-online-tmdb.vercel.app/',
    txt_site: 'Site',
    href_git: 'https://github.com/Eliel-Silva-dev/filmesOnline-tmdb',
    txt_git: 'Repositório',
    status: true,
  },
  {
    src: '/img/imgcardbaldinadvogados.jpg',
    alt: 'Imagem do projeto Baldin Advogados',
    title: 'Baldin Advogados',
    h3: 'Baldin Advogados',
    p: 'Site do escritório de advocacia Baldin, com informações sobre o escritório, as areas de atuação e contato com o escritório via formulário e WhatsApp.',
    href_site: 'https://baldin-advogados.vercel.app/',
    txt_site: 'Site',
    href_git: 'https://github.com/Eliel-Silva-dev/baldin-advogados',
    txt_git: 'Repositório',
    status: true,
  },
  {
    src: '/img/imgcardrentcars.jpg',
    alt: 'Imagem ilustrativa de projeto Rentcars',
    title: 'Rentcars - aluguel de carros',
    h3: 'Rentcar',
    p: 'Este projeto ainda esta em desenvolvimento e tem como objetivo fornecer serviços de locação de veículos de forma simples e fácil.',
    href_site: 'https://rentcars-automoveis.vercel.app/',
    txt_site: 'Site',
    href_git: 'https://github.com/Eliel-Silva-dev/rentcars',
    txt_git: 'Repositório',
    status: true,
  },
  {
    src: 'img/imgcardzeloimoveis.jpg',
    alt: 'Imagem ilustrativa do projeto zelo  imoveis',
    title: 'zelo  imoveis',
    h3: 'Zelo  Imoveis',
    p: 'Este projeto tem como objetivo apresentar, aos futuros proprietários, os serviços oferecidos pela imobiliária.',
    href_site: 'https://zelo-imoveis.vercel.app/',
    txt_site: 'Site',
    href_git: 'https://github.com/Eliel-Silva-dev/Zelo-imoveis',
    txt_git: 'Repositório',
    status: true,
  },
  {
    src: '/img/imgcardlogincadastro.png',
    alt: 'Imagem ilustrativa da página de login',
    title: 'Página de login e cadastro',
    h3: 'Página de login',
    p: 'Página de cadastro de usuários e login de acesso.',
    href_site: '/',
    txt_site: 'Site',
    href_git: '/',
    txt_git: 'Repositório',
    status: false,
  },
  {
    src: '/img/imgcardcadastro.png',
    alt: 'Imagem ilustrativa da pagina de cadastro de cides e pessoas',
    title: 'Pagina de cadastro de cidades e pessoas',
    h3: 'Cadastro',
    p: 'Página desenvolvida para cadastrar informações sobre pessoas e cidades e possibilitar uma busca personalizada com paginação.',
    href_site: '/',
    txt_site: 'Site',
    href_git: '/',
    txt_git: 'Repositório',
    status: false,
  },
  {
    src: '/img/imgcarddefault.png',
    alt: 'Imagem ilustrativa de projetos em andamento',
    title: 'Projeto em andamento',
    h3: 'Em breve',
    p: 'Trabalho em andamento',
    href_site: '/',
    txt_site: 'Site',
    href_git: '/',
    txt_git: 'Repositório',
    status: false,
  },
];

export default dataProject;
